# Generated by Django 3.2.13 on 2022-06-29 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sms_provider', models.CharField(choices=[('AIRTEL', 'AIRTEL'), ('JIO', 'JIO'), ('TWILIO', 'TWILIO')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('throughput', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSStatusDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('SENT', 'SENT'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FAILED', 'FAILED')], max_length=50)),
                ('retrigger_count', models.IntegerField(default=1)),
                ('sms_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_sender.smsproviderconfig')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSMSStatusDetails',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('phone_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('SENT', 'SENT'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FAILED', 'FAILED')], max_length=50)),
                ('retrigger_count', models.IntegerField(default=1)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sms_provider', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms_sender.smsproviderconfig')),
            ],
            options={
                'verbose_name': 'historical sms status details',
                'verbose_name_plural': 'historical sms status detailss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSMSProviderConfig',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('sms_provider', models.CharField(choices=[('AIRTEL', 'AIRTEL'), ('JIO', 'JIO'), ('TWILIO', 'TWILIO')], max_length=50)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('throughput', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sms provider config',
                'verbose_name_plural': 'historical sms provider configs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
